---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: production
  become: true
  tasks:

  - name: install basic packages for Perfect Server
    tags: nginx,php
    package:
      name: 
        - htop_package
        - fail2ban_package
      state: latest
      update_cache: yes
